### ISSUE TITLE
State Make and Use not balanced

### ISSUE THREAD

**Issue by MoLi7** [USEPA/stateior#12]
Industry output calculated from Make and Use are not the same: (`x_use` - `x_make`)/`x_make` > 0.1 for a few sectors.

**Comment by MoLi7** [comment]
Root cause is state Value Added (V001, V002, V003) that are only [allocated from](https://github.com/USEPA/stateior/blob/master/R/StateUseFunctions.R#L221) US Value Added but not balanced with state Make and Intermediate Consumption.

We should apply RAS to balance the state Value Added table (VA-by-industry) before appending it to the bottom of state Use.

**Comment by MoLi7** [comment]
We should also change calculations of industry and commodity output from using Make to using Use. See [related discussion](https://github.com/USEPA/useeior/issues/218).

⚠️ During the state Use model construction, state-US industry output ratio is needed to allocate US Use to states. In cases like this, `rowSums(StateMake)` is used as an approximation of true state industry output. Once state Use table is generated, a final state industry output and commodity output will be calculated.

**Comment by MoLi7** [comment]
Created this [two-step RAS approach](https://github.com/MoLi7/stateior/blob/dev/R/StateUseFunctions.R#L256-L295) to achieve balanced state VA table.

The rationale is, to balance the state VA table below, `t_r` needs to be balanced first.

```
              industries    t_r
          +----------------+---+
 ST1-V001 |                |   |
 ST1-V002 |                |   |
 ST1-V003 |                |   |
...       |    state VA    |   |
ST52-V001 |                |   |
ST52-V002 |                |   |
ST52-V003 |                |   |
          +----------------+---+
```

`t_r` can be reshaped to a VA-by-state `m0` like below.

```
           states
     +----------------+
V001 |                |
V002 |       m0       |
V003 |                |
     +----------------+
```
With `t_r_new = rowSums(US_ValueAdded)` and `t_c_new = sum(StateMake) - sum(StateIntermediateConsumption)`, `m0` can be RAS-balanced to `m`.

Now going back to the state VA table above, directly using the reshaped `m` as `t_r` and `colSums(US_ValueAdded)` as `t_c` will not yield a new state VA table that is balanced at state level. Instead, splitting the state VA table and `m` into state size and apply RAS to each state can assure balance between state Make and Use.

Then, for each state there is a `m0_state` below, a `t_r_state = m[, state]` and a `t_c_state = rowSums(StateMake) - colSums(StateIntermediateConsumption)`

```
         industries
     +----------------+
V001 |                |
V002 |    m0_state    |
V003 |                |
     +----------------+
```

Once each `m0_state` is balanced to `m_state`, they can be compiled to form the new state VA table.

**Comment by MoLi7** [comment]
@WesIngwersen does the approach I proposed look reasonable to you?

**Comment by WesIngwersen** [comment]
yes, the approach of balancing value added by state makes sense, where state Use is finalized and therefore industry output is finalized in Use and we want the rowSums of state Make to produce the same industry output and therefore on a state by state basis we balance the sum of the value added component to achieve this.

**Comment by MoLi7** [comment]
I've started to implement this approach in GH Actions and found applying RAS to `m0_state` for 52 times is very time consuming - may take 4-6 hours. Will have more updates later today.

**Comment by MoLi7** [comment]
State Make and Use are balanced in terms of industry output, i.e. `abs((x_make - x_use)/x_make) < 0.00001`.

**Comment by MoLi7** [comment]
However, commodity output summed from state Make and Use are not equal, i.e. `q_make ≠ q_use`, due to Imports `F050` in the Use table.
Initially, I was thinking of implementing a RAS balance on state `F050` similar to what was applied to state GVA like so:

```
                  states
            +----------------+
            |                |
commodities |       m0       |
            |                |
            +----------------+
```
where each column is the `F050` column of each state.
With `t_r = US_F050` and `t_c = colSums(StateMake) - rowSums(StateUse_exceptF050)`, `m0` can somewhat be RAS-balanced to `m`, but using the values in `m` to replace state `F050` still does not yield `q_make == q_use` at state level, largely because there are negative values involved in `F050` both at US and state levels, and it's very difficult balance at state level while keep sum of state equal to national totals.

**Comment by MoLi7** [comment]
Considering state `F050` is 1) not used in any two-region IO calculation and 2) accepted to be not sum up to US totals in validation, **I propose to estimate state `F050` simply based on the confirmed state Make and state Use (except `F050`), i.e. for each state, `F050 = colSums(Make) - rowSums(Use[, -"F050"]`.** As a result, state Make and Use will be balanced in terms of commodity output and no other IO calculations will be affected.

**Comment by MoLi7** [comment]
@WesIngwersen please let me know what you think so that I can proceed with re-creating state Use tables and two-region Use tables.

**Comment by MoLi7** [comment]
Summarizing the discussion with Christa and Joao, commodity output comparison should NOT be between **state Make** and **state Use**, instead it should be between **state Make** and **two-region Use**.

**Comment by MoLi7** [comment]
After thorough investigation and discussion with @WesIngwersen and team, we decided to

1. Regionalize the updated Use table (see `updateIO` in `useeior`) from national level to state level
2. Use the same state/US total GVA ratio that regionalizes US Make and Intermediate Consumption to regionalize national Value Add (in Use) to states. See 6dde49643ddc235d859393ff3bc21f7597642c3c

The new method should produce balanced state Make and Use in terms of industry output. This will be checked in validation.
