### ISSUE TITLE
Commodity output out of balance

### ISSUE THREAD

**Issue by bl-young** [USEPA/stateior#25]
Refactored validation reveals that commodity output is out of balance (see [2018](https://github.com/USEPA/stateior/blob/ver-0.2.1/inst/doc/output/ValidateModel_2018.md#2-check-commodity-output))

This specific validation is [new on this branch](https://github.com/USEPA/stateior/blob/ver-0.2.1/inst/doc/ValidateModel.Rmd#L75). [Prior validation](https://github.com/USEPA/stateior/blob/master/inst/doc/ValidateModel.Rmd#L68) only assessed industry output.

**Comment by WesIngwersen** [comment]
@bl-young See previous balance issue and particularly [this comment](https://github.com/USEPA/stateior/issues/12#issuecomment-1076676231) from @MoLi7 
The single region IO table commodity output is not expected to balance in our approach, but the [balances are achieved in the two-region models](https://github.com/USEPA/stateior/blob/ver-0.2.1/inst/doc/output/ValidateModel_2018.md#9-check-if-commodity-output-from-two-region-make-and-domestic-use-are-almost-equal-relative-difference--001).
There does seem to be a minor issue with the Texas 2R model that is not correctly reporting out to this md ..... but that's Texas, so should we be surprised ?!?!  ;-)

**Comment by bl-young** [comment]
Ah great thanks for pointing me to that. I was wondering if this was an expected outcome.

Should we drop check 2.1 from the validation then if we expect it to fail?

**Comment by WesIngwersen** [comment]
> Ah great thanks for pointing me to that. I was wondering if this was an expected outcome.
> 
> Should we drop check 2.1 from the validation then if we expect it to fail?

As far as I understand, then yes. But not positive on why this wasn't dropped earlier for this same reason .... 
@MoLi7 if you can recall, let us know,

**Comment by bl-young** [comment]
This [commit](https://github.com/USEPA/stateior/commit/6e8c66e777377f6d5e7e5a61390079b9bb9bdb02), adding check 2.1, was added around the time that issue (#12) was identified, but not modified further after the issue was resolved.

**Comment by MoLi7** [comment]
It looks like I messed up ValidateModel.Rmd a little in 51fd257 when I tried to solve conflicts between two branches. In its parent commit 7c52f2c, ValidateModel.Rmd should be the correct version where sum of state industry and commodity output are compared against US totals.

**Comment by bl-young** [comment]
@MoLi7 , see commit c16dd90 where I restored the original check 2 from 7c52f2c and skip over the two checks there now (2.1 and 2.2). Did I interpret correctly what you were saying?

**Comment by MoLi7** [comment]
Yes, it looks good to me. Thanks @bl-young
