### ISSUE TITLE
Error in retrieving data files from EPA Data Commons

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/stateior#31]
Code like this basic call to load data as described on main page is failing

https://github.com/USEPA/stateior/blob/03ac0e2ba0ea6a05506f7310e22f040bfaff3346/README.md?plain=1#L45

applies to latest release , v0.2.1

**Comment by WesIngwersen** [comment]
code works if the data are stored locally, but retrieval from Data Commons is failing

**Comment by bl-young** [comment]
I am able to run this code for files that need to be downloaded:
> OneRegionDomesticUse_2012 <- loadStateIODataFile("State_Summary_DomesticUse_2012")

> 2023-10-30 14:18:45 INFO::State_Summary_DomesticUse_2012_0.1.0.rds not found in local folder, downloading from Data Commons...

Note, we do have an issue with identifying the most recent version, when version is not specified. During the changeover to the new site all files now have the same generation date (which is why my code above obtained the v 0.1.0 file)

**Comment by WesIngwersen** [comment]
I ran into this with other files



>TwoRegionUse_ls <- loadStateIODataFile(paste0("TwoRegion_Summary_UsewithTrade_","2020"))
2023-10-30 14:46:11 WARNING::TwoRegion_Summary_UsewithTrade_2020 not found on Data Commons. Looking in local data directory now...

**Comment by WesIngwersen** [comment]
Looking more into the response code from the server it's "Access Denied". Not sure if there is a privileges issue or just a code returned when the file is not found
