### ISSUE TITLE
`Last modified` no longer unique for existing data commons files

### ISSUE THREAD

**Issue by bl-young** [USEPA/stateior#32]
https://github.com/USEPA/stateior/blob/03ac0e2ba0ea6a05506f7310e22f040bfaff3346/R/UtilityFunctions.R#L212-L216

> Note, we do have an issue with identifying the most recent version, when version is not specified. During the changeover to the new site all files now have the same generation date (which is why my code above obtained the v 0.1.0 file)
_Originally posted by @bl-young in https://github.com/USEPA/stateior/issues/31#issuecomment-1785803158_

**Comment by bl-young** [comment]
Should be able to sort using [numeric_version](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/numeric_version)
> sort(numeric_version(ver))

**Comment by WesIngwersen** [comment]
Please proceed with this change and close out issue, thanks
