### ISSUE TITLE
Error message when trying to access pacakge

### ISSUE THREAD

**Issue by willspisak** [USEPA/stateior#33]
Hi all I have tried to access the package as instructed 
install.packages("devtools")
devtools::install_github("USEPA/stateior@v0.2.0")
library(stateior)

But I keep getting this message 

> devtools::install_github("USEPA/stateior@v0.2.0")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref v0.2.1
  Did you spell the repo owner (`USEPA`) and repo name (`stateior`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

Spelling looks right, are there permissions required to access the package? 

Thanks

**Comment by WesIngwersen** [comment]
We had an error in our text. The text following '@' should be a tag or commit hash. The tag is just '0.2.0'. I fixed this so give it another try.

Thanks for creating this issue.

**Comment by bl-young** [comment]
and I would propose we drop the version number entirely on install to get the latest release:

> devtools::install_github("USEPA/stateior")
