### ISSUE TITLE
Specify the sequence of files

### ISSUE THREAD

**Issue by AZFARHAD24511** [USEPA/stateior#39]
The repository contains multiple files, yet there is no clarification on the order in which these files should be executed. Could you kindly furnish an explanation regarding the purpose of each file and specify the intended function of every individual file?

**Comment by bl-young** [comment]
Yes, the wiki describes the sequential approach necessary to build the model files:
https://github.com/USEPA/stateior/wiki/Model-Approach.

In particular, if you want to recreate the steps, you would:
1. `buildStateSupplyModel()`
2. `buildStateUseModel()`
3. `assembleTwoRegionIO()`

All of these functions are in BuildModel.R
